# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2850988377c507417d04cd0a1fcd8007b1f80f9cd6449ca66223ba319c90877002e4ad07e88c9c94fd033695241b0bba5f84a9d35bed38941a007e318e279351

test:
  secret_key_base: 747c387d01151fb7603c93733ae747337b86fb0b121b2292bdc7927e895c325a08cd396330c6551ce8c40ecf4a4dd2f69c2d15793804bdffda38a5f9d1d64ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
